### ISSUE TITLE
I'm unable to install Omnia

### ISSUE THREAD

**Issue by gjheaton** [FTBTeam/FTB-Omnia#137]
* **Modpack Version**: 1.7

* **Issue**: I'm unable to install. I'm receiving error when installing installer.jar. I have tried uninstalling and reinstalling Omnia and the FTB app as well.

* **Link to Log or Crash File Paste**: 
![image](https://user-images.githubusercontent.com/68754667/88960459-22795f00-d269-11ea-8d7a-8ba526122c20.png)

* **Is it Repeatable?**: Yes

**Comment by Sunekaer** [comment]
Should have been fixed, but the files have been synced around which takes time, but try install 1.6.1 and then update to 1.7.0 - that have done the trick for some people

**Comment by gjheaton** [comment]
Thank you this worked.

**Comment by Wugzi** [comment]
I am still getting this same error. Using the upgrade method did not work for me.
