### ISSUE TITLE
V1.1.0 Client Crashes Randomly

### ISSUE THREAD

**Issue by hodlhodl1132** [FTBTeam/FTB-Omnia#16]
* **Modpack Version**: 1.1.0 & 1.0.1

* **Issue**: Client will crash randomly. I will load up into a server and within anywhere between 10 seconds to an hour, the client will crash. Further details are not given in the minecraft launcher.

* **Link to Log or Crash File Paste**: [Log One](https://paste.feed-the-beast.com/view/62e91295) , [Log Two](https://paste.feed-the-beast.com/view/29218888)

* **Is it Repeatable?**: Yes, it happens every single time I play

* **Mod/s Affected**: I cannot tell

* **Known Fix**:

**Comment by Naxanria** [comment]
This looks like a faulty java install. Probably need to reinstall that.

**Comment by hodlhodl1132** [comment]
That was one of the first things I tried a re-install of java. The issue persisted after. I really don't know but my guess was that it needed elevated permissions. I tried running FTB App as Administrator and since haven't been able to recreate the issue.

**Comment by Naxanria** [comment]
Good it is fixed then :)

**Comment by hodlhodl1132** [comment]
No it is not, it is still happening.  Getting this error everytime I crash. https://java.com/en/download/help/exception_access.xml

It says I could disable UAC,  which for obvious reasons isn't a good solution

**Comment by Sunekaer** [comment]
From what i gathered on google, this is an issue with the java or os on your PC.
I haven't found any fixes

**Comment by Naxanria** [comment]
Closing as this not a pack issue.

**Comment by hodlhodl1132** [comment]
Appreciate the feedback but this doesn't happen on any other pack. Hundreds of hours I can go on other FTB packs and have no similar issues. So definitely is a pack issue.

**Comment by Naxanria** [comment]
It can be 1.15.2 Minecraft related?
This does not seem to be a problem we can fix.
